### PR TITLE
Implementation/storage repositories

### PR DESCRIPTION
**Pull request by TVAO**
Added tests for UserRepository by using the Framework Moq and then implemented CRUD operations based on this. Need to know if operations should be async and how to keep db connection open for each method call only. Please do make example in my current implementation. When this branch is validated, I will implement the other repositories.

### CODE REVIEW

**Comment by two2tee** [comment]
Vi gemmer ikke DB context som et felt længere men benytter den under hvert metode


Eksemple på using

public StoredUser read(int Id)
{
    using (var context = new DbContext()) 
    {     
        // Perform data access using the context 
     }

}



mere info kan findes ved

https://msdn.microsoft.com/en-us/data/jj729737.aspx

**Comment by two2tee** [comment]
Vi gemmer ikke DB context som et felt længere men benytter den under hvert metode


Eksemple på using

```c#
public StoredUser read(int Id)
{
    using (var context = new DbContext()) 
    {     
        // Perform data access using the context 
    }
}
```


mere info kan findes ved

https://msdn.microsoft.com/en-us/data/jj729737.aspx

**Comment by TVAO** [comment]
Man kan vel stadig godt gemme den som et felt: 

public int Create(T user)
        {
            using (_dbContext)
            { 
            _dbContext.Set<T>().Add(user);
            _dbContext.SaveChanges();
            return user.Id;
            }
        }

**Comment by TVAO** [comment]
I need to implement usings for all CRUD operations as a replacement of Dispose. Then, I need to create multiple DbContexts used for each subsystem in the ApplicationLogic (clean code). Finally, I need to test CRUD operations but also whether connection is actually closed accordingly. We could have a Repo combining subsystem entities (e.g. User and Team) with overrides.

**Comment by TVAO** [comment]
Design choices to consider: single dbcontext vs multiple dbcontexts and single repository vs multiple repositories. Either have one repository per aggregate root (e.g. StudyRepository allows to omit repo for Paper as its child) or use EF directly without repositories (all commands available). Either have one DbContext with no separation where entities relate to each other or split it by subsystems (can cause problems if entities are interrelated but allows for cleaner code and SRP).

**Comment by wmars** [comment]
Maybe some more special cases needs to be tested for database inputs to be handled e.g. null, empty objects or something similar

**Pull request closed without merging**
